class HazenWilliam{
static Map<String, double>  hw = <String, double>{ 
    "ABS" :	130,
    "Aluminum" :150,
    "Asbestos Cement"	:140,
    "Asphalt Lining" :140,
    "Brass" :140,
    "Brick sewer" :100,
    "Cast-Iron - new unlined (CIP)" :130,
    "Cast-Iron 10 years old" :113,
    "Cast-Iron 20 years old" :100,
    "Cast-Iron 30 years old" :90,
    "Cast-Iron 40 years old" :83,
    "Cast-Iron, asphalt coated" :100,
    "Cast-Iron, cement lined" :140,
    "Cast-Iron, bituminous lined" :140,
    "Cast-Iron, sea-coated" :120,
    "Cast-Iron, wrought plain" :100,
    "Cement lining" :140,
    "Concrete 100" :140,
    "Concrete lined, steel forms" :140,
    "Concrete lined, wooden forms" :120,
    "Concrete, old" :110,
    "Copper" :140,
    "Corrugated Metal" :60,
    "Ductile Iron Pipe (DIP)" :140,
    "Ductile Iron, cement lined" :120,
    "Fiber" :140,
    "Fiber Glass Pipe - FRP"	:150,
    "Galvanized iron"	:120,
    "Glass"	:130,
    "Lead"	:140,
    "Metal Pipes - smooth" :140,
    "Plastic" :150,
    "Polyethylene, PE, PEH"	:140,
    "Polyvinyl chloride, PVC, CPVC"	:150,
    "Smooth Pipes"	:140,
    "Steel new unlined" :150,
    "Steel, corrugated"	:60,
    "Steel, welded and seamless"	:100,
    "Steel, interior riveted, no projecting rivets"	:110,
    "Steel, projecting girth and horizontal rivets"	:100,
    "Steel, vitrified, spiral-riveted" :110,
    "Tin"	:130,
    "Vitrified Clay"	:110,
    "Wrought iron, plain"	:100,
    "Wooden or Masonry Pipe - Smooth"	:120,
    "Wood Stave" :120,
  };
}